/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/header/baseHeader.vue')['default']
    BaseIcon: typeof import('./src/components/common/baseIcon.vue')['default']
    BasePanel: typeof import('./src/components/panel/basePanel.vue')['default']
    CompList: typeof import('./src/components/header/compList.vue')['default']
    CtrlList: typeof import('./src/components/header/ctrlList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    TextAndInput: typeof import('./src/components/common/textAndInput.vue')['default']
  }
}
